name: Snyk Container
on:
  push:
  workflow_dispatch: 
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build a Docker image
      run: docker build -t your/image-to-test .
    - name: Run Snyk to check Docker image for vulnerabilities
      # Snyk can be used to break the build when it detects vulnerabilities.
      # In this case we want to upload the issues to GitHub Code Scanning
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        # In order to use the Snyk Action you will need to have a Snyk API token.
        # See https://docs.snyk.io/integrations/ci-cd-integrations/github-actions-integration#getting-your-snyk-token
        # or you can sign up for free at https://snyk.io/login
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN}}
      with:
        image: your/image-to-test
        args: --file=Dockerfile --sarif-file-output=snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif

  # Automatically create a PR if vulnerabilities are detected
    - name: Create pull request if vulnerabilities found
      if: always()  # Runs even if the Snyk job fails due to vulnerabilities
      uses: peter-evans/create-pull-request@v5
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fix vulnerabilities found by Snyk"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          title: "Fix vulnerabilities"
          body: "Snyk has detected vulnerabilities, this PR attempts to fix them."
          branch: "fix/snyk-vulnerabilities"
        
